url: http://192.168.1.2:5002/api/generate?property=name.findName&property=random.hp&property=random.damage&locale=tr
#https://demo.reunico.com/faker/api/generate?property=name.findName&property=name.title&property=random.number&locale=tr

camunda.bpm.admin-user:
  id: admin
  password: admin

